on: [push]

name: Continuous integration

jobs:
  build:
    name: Build SELinux module
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/almalinux/9-base:9.4
    steps:
      - name: Install dependencies
        run: |
          dnf install -y selinux-policy-targeted \
                   policycoreutils \
                   policycoreutils-devel \
                   setools-console \
                   setroubleshoot

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build module
        run: |
          make -f /usr/share/selinux/devel/Makefile cosmiand.pp
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: selinux-cosmiand-module
          path: cosmiand.pp

  push:
    needs: build
    name: Push on package.cosmian.com
    runs-on: self-hosted
    container:
      image: cosmian/docker_doc_ci
      volumes:
        - /home/cosmian/.ssh/id_rsa:/root/.ssh/id_rsa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4

      - name: Display artifacts content
        run: find .

      - name: Push latest build to package.cosmian.com
        shell: bash
        run: |
          set -x
          if [[ "${GITHUB_REF}" =~ 'refs/tags/' ]]; then
            BRANCH="${GITHUB_REF_NAME}"
          else
            BRANCH="last_build/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          fi
          DESTINATION_DIR=/mnt/package/selinux-module/$BRANCH
          ssh -o 'StrictHostKeyChecking no' -i /root/.ssh/id_rsa cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp -o 'StrictHostKeyChecking no' -i /root/.ssh/id_rsa selinux-cosmiand-module/cosmiand.pp cosmian@package.cosmian.com:$DESTINATION_DIR/
